name: Make check

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore:
      - README
      - NEWS
  pull_request:
    branches: [ master ]

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  build:
    name: Build with ${{ matrix.ucs }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true # do not compile for ucs4 if ucs2 fails
      matrix:
        ucs: [ucs2, ucs4]

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - name: Install dependencies
      run: sudo apt-get update -qq && sudo apt-get install -y libyaml-dev texinfo texlive
    - name: Autogen
      run: ./autogen.sh
    - name: Configure
      run: ./configure
      if: matrix.ucs == 'ucs2'
    - name: Configure with ucs4
      run: ./configure --enable-ucs4
      if: matrix.ucs == 'ucs4'
    - name: Make check
      run: make check
    - name: Store the test suite log
      if: ${{ always() }} # store the test suite log even if the tests failed
      uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
      with:
        name: test-suite-${{ matrix.ucs }}.log
        path: tests/test-suite.log
